#合理的配置对于运行工具很重要，配置的内容需根据不同的APP定制
#2023.08.23 by Shirley

#****************************************************UI遍历根据需要更改下面的值****************************************************
CRITICAL_ELEMENT:

  #---Android---
  #Android App测试时，需指定App包名和启动的Activity
  ANDROID_PACKAGE: com.voyah.car
  ANDROID_MAIN_ACTIVITY: 
  #通过xpath过滤出要点击的元素， 注意值两侧要加单引号''
  ANDROID_CLICK_XPATH_HEADER: ' ( string-length(@text)<30  or contains(@text,"允许") ) '
  #若App顶、底含有TabBar, 需指定TabBar的id, 若无TabBar注释下行。 多个id时用or拼接: 如'@resource-id="id1" or @resource-id="id2"'
  # ANDROID_BOTTOM_TAB_BAR_ID: '@resource-id="android:id/tabs"'

#****************************************************Monkey测试时根据需要更改下面的值，调节事件发生概率****************************************************
#每项为事件随机发生的次数，各项之和为100
MONKEY:
  #滑动
  SWIPE_RATIO: 5
  #点击
  CLICK_RATIO: 70
  #点击 MONKEY_SPECIAL_POINT_LIST 中的坐标 主要用于触发"返回"功能
  CLICK_SPECIAL_POINT_RATIO: 2
  #重启app
  RESTART_APP_RATIO: 0
  #长按
  LONG_PRESS_RATIO: 1
  #触发Home键 (Android Only)
  HOME_KEY_RATIO: 0
  #触发Back Key
  BACK_KEY_RATIO: 0
  #手势操作
  #双击
  DOUBLE_TAP_RATIO: 2
  #缩小(两指)
  PINCH_RATIO: 2
  #放大(两指)
  UNPINCH_RATIO: 2
  #拖拽
  DRAG_RATIO: 4
  #CLICK_ITEM_XPATH_LIST中指定元素的点击次数
  CLICK_ITEM_BY_XPATH_RATIO: 1

#2023.08.23 by Shirley
#（可选）Monkey的一些特殊事件
MONKEY_SPECIAL_ACTION:

  #设置需要点击的元素的xpath，点击次数由 CLICK_ITEM_BY_XPATH_RATIO 控制， 若找不到相应的元素则会忽略该事件
  CLICK_ITEM_XPATH_LIST:
  #- '//*[@resource-id="com.xes.jazhanghui.activity:id/tv_item_course"]'

  #点击特定的点，如：(x,y)为back键的位置时,触发"后退"操作，避免在一个页面停留时间太久
  MONKEY_SPECIAL_POINT_LIST:
    - '80,160'

  #根据坐标长按某点10秒
  LONG_PRESS_LIST:
    - '100,250'

  #设置不点击的区域(圆形)， radius为圆半径， 坐标为不想点击区域的圆心
  MONKEY_BLACKLIST_POINT_LIST:
    - 'radius,10'
    - '0,0'


#****************************************************以下内容通常不需要修改****************************************************
#2023.08.23 by Shirley
#（可选）以下各值主要用于提高测试的效率，根据app着情修改或者不改
LIST:
  #UI元素中出现下列文字时 触发back键(iOS 由左向右划触发返回操作)
  PRESS_BACK_TEXT_LIST:
    - 返回

  #当pp跳转到以下app时 触发back键
  PRESS_BACK_PACKAGE_LIST:
    - com.autonavi.minimap

  #当前遇到以下Activity时 触发back键 (Android only)
  PRESS_BACK_ACTIVITY_LIST:
    - .mvp.servicecenter.view.ServiceCenterMapDetailActivity


  #待输入文本的控制类型
  INPUT_CLASS_LIST:
    - android.widget.TextView
    - XCUIElementTypeTextField
    - XCUIElementTypeSecureTextField

  #待输入的文本（随机选中后选列表中的一个）
  INPUT_TEXT_LIST:
    - '123'
    - 'ABC'
  #除了APP本身的包名外 根据以下包名判断是否跳出了APP,当app跳转到以下app时被认为是合法，会继续遍历操作
  ANDROID_VALID_PACKAGE_LIST:
    - com.miui.securitycenter

  #同ANDROID_VALID_PACKAGE_LIST
  IOS_VALID_BUNDLE_LIST:


  #白名单，遇到包含以下文本的控件，会多次点击（默认所有控件只点一次）
  ITEM_WHITE_LIST:
    - 确定
    - 允许
    - 退出
    - 取消
    - 已解决
    - 提交

  #不点击包含以下文本的控件
  ITEM_BLACKLIST:

  #不点击以下类型的元素
  ANDROID_EXCLUDE_TYPE:
    - android.widget.FrameLayout
    - android.widget.ImageButton

  #解释待续
  NODE_NAME_EXCLUDE_LIST:
    - selected
    - instance
    - checked
    - naf
    - content

  #解释待续
  STRUCTURE_NODE_NAME_EXCLUDE_LIST:
    #Android
    - text


#****************************************************以下内容通常不需要修改****************************************************
#2023.08.23 by Shirley
#一些全局的配置
GENERAL:
  #截屏数量限制
  SCREENSHOT_COUNT: 5000
  #达到截屏限制数量时删除所有截屏
  # ENABLE_DELETE_SCREEN: false
  #Crash时截图显示步骤数量
  CRASH_PIC_COUNT: 10
  #遍历深度
  MAX_DEPTH: 800
  #点击次数
  MAX_CLICK_COUNT: 1000000
  #查找元素的时间
  DEFAULT_WAIT_SEC: 3
  #查找元素的间隔时间
  DEFAULT_POLLING_INTERVAL_SEC: 2
  #是否忽略Crash,设为true时,crash后会重启app然后继续遍历
  IGNORE_CRASH: true
  #遍历的过程中进行向上划动操作  ！！！此项会加长遍历时间！！！
  ENABLE_VERTICAL_SWIPE: false
  #运行时间限制(分钟)
  CRAWLER_RUNNING_TIME: 720
  #控制是否生成视频
  GENERATE_VIDEO: true
  #控制视频方向，竖屏或模屏
  VIDEO_VERTICAL: true
  #每个UI变化X次时，检测是否需要自动登录
  USER_LOGIN_INTERVVAL: 5
  #忽略底部元素Bounds值
  #REMOVE_BOTTOM_BOUND: false

#一些默认值
DEFAULT_VALUE:
  #0.0.0.0代表Appium Server运行在本地
  APPIUM_SERVER_IP: 0.0.0.0
  #Appium端口
  PORT: 4723
  #IOS WDA_PORT
  IOS_WDA_PORT: 8100

#2023.08.23 by Shirley
#输出更多的log 主要用于调试工具用
LOG:
  #将性能数据写入数据库相关的log
  DB_LOG: false
  #性能数据相关log
  PERF_LOG: false
  #是否开启DOM树在log中的显示
  DOM_DISPLAY: false

#时序数据库 用于记录性能数据 与-e 一起使用
INFLUXDB:
  DB_PORT: 8086
  DB_IP: localhost

#*******************ENABLE_AUTO_LOGIN 为true里需要修改以下内容**************************
#（可选）自动登录时查找控件所需要的信息,当找到列表中第一个元素时会按顺序操作以下元素。注意xpath中的属性值要加双引号""
#如果不需要自动登录功能以下值不需要修改
LOGIN_ELEMENTS:
  #开启自动登录功能
  ENABLE_AUTO_LOGIN: false
